---
apiVersion: v1
kind: Service
metadata:
  name: spring-application
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:    
    app.kubernetes.io/name: myapp
    app.kubernetes.io/instance: myapp
spec:
  replicas: 2
  selector:docker 
    matchLabels:
      app.kubernetes.io/name: myapp
      app.kubernetes.io/instance: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
        app.kubernetes.io/instance: myapp
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: myapp
          image: dellopsinternal.jfrog.io/code-docker/spring-application:9
          command: ["/bin/sh"]
          args: ["-c","sh java -jar spring.jar;while true; do echo hello; sleep 10;done"]
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          resources:
            requests:
              memory: 0.25Gi
              cpu: 0.5
            limits:
              memory: 0.25Gi 
              cpu: 0.5
